version: '3.6'

services:
  postgreDB: 
    image: postgres
    restart: always
    container_name: postgres_todoApp
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}

volumes:
  postgres-data: 
    name: todoapp_postgres_data